'use client';
import {useState,useRef,useEffect,useId} from 'react';
import {Switch} from '@/components/ui/switch';
import {newStudy,studyView,studyEvent,nextTrial,canSubmit,canStart,canFinishTask,canComplete,exportStudy} from '@/lib/study.mjs';
import {PRE_QUESTIONS,POST_QUESTIONS,POST_TEXT_QUESTIONS,FINAL_QUESTION} from '@/lib/study-surveys.mjs';
import products from '@/lib/products.json';
const won=(v:number)=>`${v.toLocaleString('ko-KR')}원`;
function Choices({label,options,value,onChange}:{label:string,options:any[],value:any,onChange:(v:any)=>void}){const id=useId();return <div className="study-question"><p id={id}>{label}</p><div className="study-buttons" role="radiogroup" aria-labelledby={id}>{options.map(o=><button type="button" role="radio" key={o.value} aria-checked={value===o.value} onClick={()=>onChange(o.value)}>{o.label}</button>)}</div></div>}
export default function Study(){
 const [agreed,setAgreed]=useState(false);const [session,setSession]=useState<any>(null);const [downloaded,setDownloaded]=useState(false);const latest=useRef<any>(null);latest.current=session;
 const update=(s:any)=>{latest.current=s;setSession(s);setDownloaded(false)};
 const dispatch=(event:any)=>{if(latest.current)update(studyEvent(latest.current,event,performance.now(),products))};
 const start=()=>{if(!agreed||latest.current)return;update(newStudy(crypto.randomUUID(),crypto.getRandomValues(new Uint32Array(1))[0]%4,performance.now()))};
 const save=()=>{if(!session)return;const blob=new Blob([JSON.stringify(exportStudy(session),null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`PASS-${session.id}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setDownloaded(true)};
 const v=session?.current?studyView(session.current,products):null;
 const phase=session?.status??'intro';
 useEffect(()=>{window.scrollTo(0,0);document.querySelector<HTMLElement>('.study h1')?.focus();},[phase,session?.index]);
 const count=(questions:any[],answers:any)=>questions.filter(q=>q.options.some((o:any)=>o.value===answers[q.key])).length;
 const textQuestion=(q:any,value:string,onChange:(v:string)=>void)=><div className="study-question" key={q.key}><label htmlFor={`survey-${q.key}`}>{q.label} <span className="note">(선택)</span></label><textarea id={`survey-${q.key}`} rows={3} maxLength={1000} value={value||''} onChange={e=>onChange(e.target.value)} /><small>{(value||'').length} / 1,000자</small></div>;
 const stopButton=<button className="reset" onClick={()=>dispatch({type:'stop'})}>평가 중단</button>;
 const step=phase==='intro'||phase==='pre'?0:phase==='running'||phase==='post'||phase==='between'?1:2;
 return <main className="study"><header><a className="brand" href="/">마음</a><span>추천 설명 평가</span></header><ol className="study-progress" aria-label="평가 진행 단계">{['사전 설문','두 과제 · 사후 설문','최종 비교'].map((label,i)=><li key={label} aria-current={i===step?'step':undefined}>{i+1}. {label}</li>)}</ol>
 {!session?<section className="panel study-intro"><h1 tabIndex={-1}>명절 선물 선택 경험을 들려주세요</h1><p>먼저 쇼핑 경험에 관한 사전 설문 5개에 답합니다. 이어 두 가지 선물 과제를 각각 수행하고, 과제마다 사후 설문에 답한 뒤 마지막으로 두 화면을 비교합니다. 상품을 선택하지 못했다는 응답도 가능합니다.</p><p>상품은 모두 실험용이며 실제 구매는 진행하지 않습니다. 이름이나 연락처는 묻지 않습니다. 연령대·쇼핑 경험·선택·예산 변경·설문 답변·소요 시간은 이 화면에만 기록되고 자동으로 서버에 전송되지 않습니다.</p><p>마지막에 JSON 파일을 저장해 연구 담당자에게 직접 전달할 수 있습니다. 새로고침하거나 화면을 떠나면 저장하지 않은 기록은 사라집니다. 언제든 중단할 수 있습니다. 자유 응답은 선택 사항이며 이름·연락처 등 개인정보는 적지 마세요.</p><div className="study-consent"><Switch id="study-consent" checked={agreed} onCheckedChange={setAgreed}/><label htmlFor="study-consent">기록 항목과 이용 방법을 읽었고 평가를 시작하겠습니다.</label></div><button className="send" disabled={!agreed} onClick={start}>사전 설문 시작</button><p className="note">이 화면은 수업용 파일럿 도구입니다. 참여자 모집·동의 절차는 연구 담당자가 별도로 준비해야 합니다.</p></section>:
 session.status==='pre'?<section className="panel study-intro"><span className="eyebrow">시작 전 · 사전 설문</span><h1 tabIndex={-1}>평소 쇼핑 경험을 알려주세요</h1><p>정답은 없습니다. 최근 경험에 가장 가까운 답을 골라주세요. 연령대는 ‘응답하지 않음’을 선택할 수 있습니다.</p>{PRE_QUESTIONS.map((q:any)=><Choices key={q.key} label={q.label} options={q.options} value={session.preSurvey.answers[q.key]} onChange={value=>dispatch({type:'pre_answer',key:q.key,value})}/>)}<p role="status">{count(PRE_QUESTIONS,session.preSurvey.answers)} / 5개 응답 완료</p><button className="send" disabled={!canStart(session)} onClick={()=>dispatch({type:'pre_submit'})}>사전 설문 완료 · 첫 과제 시작</button>{stopButton}</section>:
 session.status==='running'&&v?<>
 <section className="panel study-task"><span className="eyebrow">과제 {session.index+1} / 2</span><h1 tabIndex={-1}>{v.task.title}</h1><p>{v.task.description}</p><p>배송비를 포함한 총예산 {won(v.baseline.budget.amount_krw)}과 {won(v.alternative.amount)}을 비교하고, 선택할 상품을 정해주세요.</p><Choices label="살펴볼 총예산" value={session.current.budget} options={[{value:'base',label:`처음 예산 ${won(v.baseline.budget.amount_krw)}`},{value:'higher',label:`비교 예산 ${won(v.alternative.amount)}`}]} onChange={value=>dispatch({type:'budget',value})}/></section>
 <section aria-labelledby="study-products"><h2 id="study-products">지금 예산에서 고를 수 있는 선물</h2><p className="status">배송비 포함 총예산 {won(v.state.budget.amount_krw)}</p><div className="cards">{v.result.items.map((p:any,i:number)=><article className="product" key={p.id}><span>추천 {i+1}</span><h3>{p.name.replace('가상 ','')}</h3><p className="price">{won(p.total)}<small> · 배송비 포함</small></p><p className="reason">{p.sweetness==='unsweetened'?'단맛이 없는 상품으로 덜 단 선호에 맞습니다.':'현재 지정한 필수 조건을 통과했습니다.'} 총예산과 제외 조건에 맞습니다.</p><button className="study-pick" aria-pressed={session.current.selectedId===p.id} onClick={()=>dispatch({type:'select',value:p.id})}>{session.current.selectedId===p.id?'선택한 선물':'이 선물 선택'}</button></article>)}</div><button className="study-none" aria-pressed={session.current.selectedId==='none'} onClick={()=>dispatch({type:'select',value:'none'})}>선택하지 못했어요</button></section>
 {session.current.condition==='B'&&<section className="panel study-comparison" aria-labelledby="study-comparison"><h2 id="study-comparison">두 예산에서는 무엇이 달라지나요?</h2><p>{won(v.baseline.budget.amount_krw)} → {won(v.alternative.amount)} · 다른 조건은 그대로입니다.</p><p><strong>{v.alternative.effectText}</strong></p><p>{v.alternative.exclusionReason.replaceAll('총예산','예산')}</p><p>{v.alternative.rankingReason}</p><p>새 후보: {v.alternative.target.name.replace('가상 ','')} · 비교 예산에서 {v.alternative.targetRank}위</p></section>}
 <section className="panel study-survey"><h2>선택을 마쳤나요?</h2><p>두 예산을 모두 살펴보고 선물 하나를 선택하거나 ‘선택하지 못했어요’를 눌러주세요. 사후 설문으로 이동하면 이 과제의 선택은 확정됩니다.</p><p role="status">두 예산 확인: {session.current.visitedBudgets.length} / 2 · {session.current.selectedId?'선택 완료':'선택 필요'}</p><button className="send" disabled={!canFinishTask(session.current)} onClick={()=>dispatch({type:'task_finish'})}>선택 확정 · 사후 설문</button>{stopButton}</section>
 </>:session.status==='post'?<section className="panel study-intro"><span className="eyebrow">과제 {session.index+1} / 2 · 사후 설문</span><h1 tabIndex={-1}>방금 사용한 화면은 어땠나요?</h1><p>{v?.task.title} 과제를 떠올리며 답해주세요. 이해도 질문은 ‘모르겠음’도 선택할 수 있습니다.</p>{POST_QUESTIONS.map((q:any)=><Choices key={q.key} label={q.key==='confidence'&&session.current.selectedId==='none'?'선택하지 않기로 한 판단이 적절하다고 얼마나 확신하나요?':q.label} options={q.options} value={session.current.answers[q.key]} onChange={value=>dispatch({type:'answer',key:q.key,value})}/>)}<h2>선택한 이유를 들려주세요</h2><p className="note">아래 3개 질문은 선택 사항입니다. 개인정보는 적지 마세요.</p>{POST_TEXT_QUESTIONS.map((q:any)=>textQuestion(q,session.current.answers[q.key],value=>dispatch({type:'answer',key:q.key,value})))}<p role="status">필수 {count(POST_QUESTIONS,session.current.answers)} / 4개 응답 완료</p><button className="send" disabled={!canSubmit(session.current)} onClick={()=>dispatch({type:'submit'})}>이 과제의 사후 설문 제출</button>{stopButton}</section>:session.status==='between' ?<section className="panel study-intro"><h1 tabIndex={-1}>첫 과제를 마쳤습니다</h1><p>잠시 쉬어도 괜찮습니다. 다음 과제는 다른 선물 상황입니다. 시작 버튼을 누르면 다음 과제의 시간 기록이 시작됩니다.</p><button className="send" onClick={()=>update(nextTrial(latest.current,performance.now()))}>두 번째 과제 시작</button><button className="reset" onClick={()=>dispatch({type:'stop'})}>여기서 마치기</button></section>:session.status==='final'?<section className="panel study-intro"><span className="eyebrow">마지막 · 최종 비교</span><h1 tabIndex={-1}>두 화면을 비교해주세요</h1><p>첫 번째 과제: {session.trials[0].taskId==='parents'?'부모님께 드릴 선물':'친구에게 보낼 선물'}<br/>두 번째 과제: {session.trials[1].taskId==='parents'?'부모님께 드릴 선물':'친구에게 보낼 선물'}</p><Choices label={FINAL_QUESTION.label} options={FINAL_QUESTION.options} value={session.finalSurvey.answers.preference} onChange={value=>dispatch({type:'final_answer',key:'preference',value})}/>{textQuestion({key:'reason',label:'그렇게 답한 이유를 설명해주세요.'},session.finalSurvey.answers.reason,value=>dispatch({type:'final_answer',key:'reason',value}))}<p className="note">이유는 선택 사항입니다. 개인정보는 적지 마세요.</p><button className="send" disabled={!canComplete(session)} onClick={()=>dispatch({type:'final_submit'})}>최종 설문 완료</button>{stopButton}</section>:<section className="panel study-intro"><h1 tabIndex={-1}>{session.status==='complete'?'평가를 마쳤습니다':'평가를 중단했습니다'}</h1><p>완료한 과제 {session.trials.length}개 · 기록 {session.events.length}건. 파일에는 무작위 세션 번호, 사전 설문, 과제별 사후 설문, 최종 비교 응답과 선택·소요 시간이 들어갑니다. 중단했다면 미완료 상태도 구분됩니다.</p><button className="send" onClick={save}>평가 기록 저장 (JSON)</button>{downloaded&&<p role="status">파일 저장을 요청했습니다. 다운로드 목록에서 확인해주세요.</p>}<p>저장한 파일은 연구 담당자에게 직접 전달해주세요. 이 화면에서는 자동으로 제출되지 않습니다.</p><a href="/">일반 선물 대화로 돌아가기</a></section>}
 <footer>두 설명 조건의 순서와 과제 조합은 무작위 배정됩니다. 설문은 이 연구를 위해 만든 문항이며, SUS·NASA-TLX 표준 척도 점수로 해석하지 않습니다.</footer></main>
}
