'use client';
import {useState,useRef} from 'react';
import {Switch} from '@/components/ui/switch';
import {newStudy,studyView,studyEvent,nextTrial,canSubmit,exportStudy} from '@/lib/study.mjs';
import products from '@/lib/products.json';
const won=(v:number)=>`${v.toLocaleString('ko-KR')}원`;
function Choices({label,options,value,onChange}:{label:string,options:any[],value:any,onChange:(v:any)=>void}){return <div className="study-question" role="group" aria-label={label}><p>{label}</p><div className="study-buttons">{options.map(o=><button type="button" key={o.value} aria-pressed={value===o.value} onClick={()=>onChange(o.value)}>{o.label}</button>)}</div></div>}
const scales=[{key:'effort',label:'상품을 비교하고 결정하는 과정은 얼마나 어려웠나요?',low:'매우 쉬움',high:'매우 어려움'},{key:'confidence',label:'자신의 선택에 얼마나 확신이 있나요?',low:'전혀 없음',high:'매우 높음'},{key:'pressure',label:'더 많은 돈을 써야 한다는 압박을 얼마나 느꼈나요?',low:'전혀 없음',high:'매우 높음'}];
export default function Study(){
 const [agreed,setAgreed]=useState(false);const [session,setSession]=useState<any>(null);const [downloaded,setDownloaded]=useState(false);const latest=useRef<any>(null);latest.current=session;
 const update=(s:any)=>{latest.current=s;setSession(s);setDownloaded(false)};
 const dispatch=(event:any)=>{if(latest.current)update(studyEvent(latest.current,event,performance.now(),products))};
 const start=()=>{if(!agreed||latest.current)return;update(newStudy(crypto.randomUUID(),crypto.getRandomValues(new Uint32Array(1))[0]%4,performance.now()))};
 const save=()=>{if(!session)return;const blob=new Blob([JSON.stringify(exportStudy(session),null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`PASS-${session.id}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setDownloaded(true)};
 const v=session?studyView(session.current,products):null;
 return <main className="study"><header><a className="brand" href="/">마음</a><span>추천 설명 평가</span></header>
 {!session?<section className="panel study-intro"><h1>두 가지 설명 방식을 사용해 보세요</h1><p>가상의 명절 선물을 고르는 과제 두 개입니다. 각 과제에서 두 예산을 살펴보고 선물 하나를 선택한 뒤 짧은 질문에 답합니다. 선택하지 못했다는 응답도 가능합니다.</p><p>상품은 모두 실험용이며 실제 구매는 진행하지 않습니다. 이름이나 연락처는 묻지 않습니다. 선택·예산 변경·답변·소요 시간은 이 화면에만 기록되고 자동으로 서버에 전송되지 않습니다.</p><p>마지막에 JSON 파일을 저장해 연구 담당자에게 직접 전달할 수 있습니다. 새로고침하거나 화면을 떠나면 저장하지 않은 기록은 사라집니다. 언제든 중단할 수 있습니다.</p><div className="study-consent"><Switch id="study-consent" checked={agreed} onCheckedChange={setAgreed}/><label htmlFor="study-consent">기록 항목과 이용 방법을 읽었고 평가를 시작하겠습니다.</label></div><button className="send" disabled={!agreed} onClick={start}>첫 과제 시작</button><p className="note">이 화면은 수업용 파일럿 도구입니다. 참여자 모집·동의 절차는 연구 담당자가 별도로 준비해야 합니다.</p></section>:
 session.status==='running'&&v?<>
 <section className="panel study-task"><span className="eyebrow">과제 {session.index+1} / 2</span><h1>{v.task.title}</h1><p>{v.task.description}</p><p>배송비를 포함한 총예산 {won(v.baseline.budget.amount_krw)}과 {won(v.alternative.amount)}을 비교하고, 선택할 상품을 정해주세요.</p><Choices label="살펴볼 총예산" value={session.current.budget} options={[{value:'base',label:`처음 예산 ${won(v.baseline.budget.amount_krw)}`},{value:'higher',label:`비교 예산 ${won(v.alternative.amount)}`}]} onChange={value=>dispatch({type:'budget',value})}/></section>
 <section aria-labelledby="study-products"><h2 id="study-products">지금 예산에서 고를 수 있는 선물</h2><p className="status">배송비 포함 총예산 {won(v.state.budget.amount_krw)}</p><div className="cards">{v.result.items.map((p:any,i:number)=><article className="product" key={p.id}><span>추천 {i+1}</span><h3>{p.name.replace('가상 ','')}</h3><p className="price">{won(p.total)}<small> · 배송비 포함</small></p><p className="reason">{p.sweetness==='unsweetened'?'단맛이 없는 상품으로 덜 단 선호에 맞습니다.':'현재 지정한 필수 조건을 통과했습니다.'} 총예산과 제외 조건에 맞습니다.</p><button className="study-pick" aria-pressed={session.current.selectedId===p.id} onClick={()=>dispatch({type:'select',value:p.id})}>{session.current.selectedId===p.id?'선택한 선물':'이 선물 선택'}</button></article>)}</div><button className="study-none" aria-pressed={session.current.selectedId==='none'} onClick={()=>dispatch({type:'select',value:'none'})}>선택하지 못했어요</button></section>
 {session.current.condition==='B'&&<section className="panel study-comparison" aria-labelledby="study-comparison"><h2 id="study-comparison">두 예산에서는 무엇이 달라지나요?</h2><p>{won(v.baseline.budget.amount_krw)} → {won(v.alternative.amount)} · 다른 조건은 그대로입니다.</p><p><strong>{v.alternative.effectText}</strong></p><p>{v.alternative.exclusionReason.replaceAll('총예산','예산')}</p><p>{v.alternative.rankingReason}</p><p>새 후보: {v.alternative.target.name.replace('가상 ','')} · 비교 예산에서 {v.alternative.targetRank}위</p></section>}
 <section className="panel study-survey"><h2>선택을 마친 뒤 답해주세요</h2><Choices label="처음 예산에서 비교 예산으로 바꾸면 첫 번째 추천 상품이 달라지나요?" options={[{value:'yes',label:'달라져요'},{value:'no',label:'같아요'},{value:'unsure',label:'잘 모르겠어요'}]} value={session.current.answers.topChanged} onChange={value=>dispatch({type:'answer',key:'topChanged',value})}/>{scales.map(s=><div key={s.key}><Choices label={s.label} value={session.current.answers[s.key]} options={[1,2,3,4,5].map(n=>({value:n,label:`${n}${n===1?' · '+s.low:n===5?' · '+s.high:''}`}))} onChange={value=>dispatch({type:'answer',key:s.key,value})}/></div>)}<p className="status">상품 선택(또는 선택하지 못함)과 질문 4개에 답하면 제출할 수 있습니다.</p><button className="send" disabled={!canSubmit(session.current)} onClick={()=>dispatch({type:'submit'})}>이 과제 제출</button><button className="reset" onClick={()=>dispatch({type:'stop'})}>평가 중단</button></section>
 </>:session.status==='between'?<section className="panel study-intro"><h1>첫 과제를 마쳤습니다</h1><p>잠시 쉬어도 괜찮습니다. 다음 과제는 다른 선물 상황입니다. 시작 버튼을 누르면 다음 과제의 시간 기록이 시작됩니다.</p><button className="send" onClick={()=>update(nextTrial(latest.current,performance.now()))}>두 번째 과제 시작</button><button className="reset" onClick={()=>dispatch({type:'stop'})}>여기서 마치기</button></section>:<section className="panel study-intro"><h1>{session.status==='complete'?'평가를 마쳤습니다':'평가를 중단했습니다'}</h1><p>완료한 과제 {session.trials.length}개 · 기록 {session.events.length}건. 파일에는 무작위 세션 번호, 설명 조건, 선택·응답 및 경과 시간이 들어갑니다. 중단했다면 미완료 상태도 구분됩니다.</p><button className="send" onClick={save}>평가 기록 저장 (JSON)</button>{downloaded&&<p role="status">파일 저장을 요청했습니다. 다운로드 목록에서 확인해주세요.</p>}<p>저장한 파일은 연구 담당자에게 직접 전달해주세요. 이 화면에서는 자동으로 제출되지 않습니다.</p><a href="/">일반 선물 대화로 돌아가기</a></section>}
 <footer>두 설명 조건의 순서와 과제 조합은 무작위 배정됩니다. 비교 설명의 효과는 실제 참여자 평가 후 분석합니다.</footer></main>
}
