import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {assignment,newStudy,studyView,studyEvent,nextTrial,canSubmit,canStart,canComplete,exportStudy,TASKS} from '../lib/study.mjs';
import {PRE_QUESTIONS} from '../lib/study-surveys.mjs';
const products=JSON.parse(readFileSync(new URL('../lib/products.json',import.meta.url)));
const event=(s,e,time=1000)=>studyEvent(s,e,time,products);
function started(id='anon',group=0,now=0){let s=newStudy(id,group,now);for(const q of PRE_QUESTIONS)s=event(s,{type:'pre_answer',key:q.key,value:q.options[0].value},now);return event(s,{type:'pre_submit'},now);}
function finish(s){s=event(s,{type:'budget',value:'higher'});s=event(s,{type:'select',value:'none'});s=event(s,{type:'task_finish'});s=event(s,{type:'answer',key:'candidateCount',value:'more'});for(const key of ['effort','confidence'])s=event(s,{type:'answer',key,value:3});s=event(s,{type:'answer',key:'topChanged',value:'no'});return event(s,{type:'submit'},2000);}
test('four assignments counterbalance task, condition and position',()=>{const seq=[0,1,2,3].map(assignment);for(const id of TASKS.map(t=>t.id))for(const c of ['A','B'])for(const i of [0,1])assert.equal(seq.filter(s=>s[i].taskId===id&&s[i].condition===c).length,1);});
test('same task and budget return identical products for A and B',()=>{for(const task of TASKS)for(const budget of ['base','higher']){const a=studyView({taskId:task.id,condition:'A',budget},products);const b=studyView({taskId:task.id,condition:'B',budget},products);assert.deepEqual(a.result,b.result);assert.equal(a.state.budget.shipping_included,true);}});
test('comparison budgets add eligible candidates without inventing a first-rank change',()=>{for(const task of TASKS){const a=studyView({taskId:task.id,budget:'base'},products);const b=studyView({taskId:task.id,budget:'higher'},products);assert.equal(a.topChanged,false);assert.ok(b.result.items.length>a.result.items.length);assert.ok(b.result.items.some(p=>p.id===a.alternative.target.id));}});
test('cannot submit incomplete ratings or inject invalid actions',()=>{let s=started('anon',0,0);assert.equal(canSubmit(s.current),false);for(const e of [{type:'submit'},{type:'select',value:'unknown'},{type:'budget',value:'bad'},{type:'answer',key:'effort',value:6},{type:'answer',key:'name',value:'private'}])assert.deepEqual(event(s,e),s);});
test('lowering budget clears a now-ineligible selection',()=>{let s=event(started('anon',0,0),{type:'budget',value:'higher'});const v=studyView(s.current,products);s=event(s,{type:'select',value:v.alternative.target.id});s=event(s,{type:'budget',value:'base'});assert.equal(s.current.selectedId,null);});
test('completed trial cannot submit twice and break time is excluded from next trial',()=>{const first=finish(started('anon',0,0));assert.equal(first.status,'between');assert.equal(first.trials.length,1);assert.deepEqual(event(first,{type:'submit'},2500),first);const second=nextTrial(first,10000);assert.deepEqual(second.current.answers,{});assert.equal(second.current.startedAt,10000);const complete=finishAt(second,12000);assert.equal(complete.status,'final');assert.equal(complete.trials[1].durationMs,2000);});
function finishAt(s,now){s=event(s,{type:'budget',value:'higher'},now);s=event(s,{type:'select',value:'none'},now);s=event(s,{type:'task_finish'},now);for(const key of ['effort','confidence'])s=event(s,{type:'answer',key,value:2},now);s=event(s,{type:'answer',key:'topChanged',value:'no'},now);s=event(s,{type:'answer',key:'candidateCount',value:'more'},now);return event(s,{type:'submit'},now);}
test('stopping records incomplete data and prevents further actions',()=>{const s=event(started('anon',1,0),{type:'stop'},700);assert.equal(s.status,'stopped');assert.equal(s.trials.length,0);assert.deepEqual(event(s,{type:'select',value:'none'}),s);const between=event(finish(started('anon',0,0)),{type:'stop'},3000);assert.equal(between.events.at(-1).type,'stop');assert.equal(between.trials.length,1);});
test('exports are snapshots without raw user text and with trial definitions',()=>{const s=finish(started('random-id',0,0));const out=exportStudy(s);assert.equal(out.startedAt,undefined);assert.equal(out.trials[0].startedAt,undefined);assert.equal(out.taskDefinitions.length,2);assert.equal(out.trials[0].comprehensionCorrect,true);out.current.answers.effort=1;assert.equal(s.current.answers.effort,3);assert.equal(out.messages,undefined);assert.ok(out.events.every(e=>!('text' in e)&&!('user' in e)));});

test('pre survey gates tasks and only accepts declared fields',()=>{let s=newStudy('anon',0,0);assert.equal(s.status,'pre');assert.equal(s.current,null);assert.equal(canStart(s),false);for(const e of [{type:'pre_submit'},{type:'select',value:'none'},{type:'pre_answer',key:'name',value:'private'}])assert.deepEqual(event(s,e),s);s=started('anon',0,5000);assert.equal(s.status,'running');assert.equal(s.current.startedAt,5000);});
test('task and survey are separate; survey cannot change the committed choice',()=>{let s=started();s=event(s,{type:'select',value:'none'},2000);assert.deepEqual(event(s,{type:'task_finish'},3000),s);s=event(s,{type:'budget',value:'higher'},3000);s=event(s,{type:'task_finish'},4000);assert.equal(s.status,'post');assert.deepEqual(event(s,{type:'budget',value:'base'},5000),s);assert.equal(s.current.taskDurationMs,4000);s=event(s,{type:'answer',key:'feedback',value:'説明が難しい'},5000);assert.equal(s.current.answers.feedback,'説明が難しい');assert.ok(!s.events.some(e=>e.value==='説明が難しい'));assert.deepEqual(event(s,{type:'answer',key:'feedback',value:'x'.repeat(1001)}),s);});
test('final survey is required and preference maps to the assigned condition',()=>{let s=finishAt(nextTrial(finish(started()),10000),12000);assert.equal(s.status,'final');assert.equal(canComplete(s),false);assert.deepEqual(event(s,{type:'final_submit'},13000),s);s=event(s,{type:'final_answer',key:'preference',value:'second'},13000);s=event(s,{type:'final_answer',key:'reason',value:'違いを理解できた'},14000);s=event(s,{type:'final_submit'},15000);assert.equal(s.status,'complete');assert.equal(s.finalSurvey.preferredCondition,s.sequence[1].condition);const out=exportStudy(s);assert.equal(out.finalSurvey.startedAt,undefined);assert.equal(out.trials[1].surveyStartedAt,undefined);assert.equal(out.finalSurvey.answers.reason,'違いを理解できた');assert.equal(out.trials[0].candidateCountCorrect,true);assert.equal(out.surveyDefinitions.pre.length,5);});
test('stop from pre and final preserves partial responses and exports safely',()=>{const pre=event(newStudy('anon',0,0),{type:'stop'});assert.equal(exportStudy(pre).current,null);const final=finishAt(nextTrial(finish(started()),10000),12000);assert.equal(event(final,{type:'stop'}).status,'stopped');});
