import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {assignment,newStudy,studyView,studyEvent,nextTrial,canSubmit,exportStudy,TASKS} from '../lib/study.mjs';
const products=JSON.parse(readFileSync(new URL('../lib/products.json',import.meta.url)));
const event=(s,e,time=1000)=>studyEvent(s,e,time,products);
function finish(s){s=event(s,{type:'select',value:'none'});for(const key of ['effort','confidence','pressure'])s=event(s,{type:'answer',key,value:3});s=event(s,{type:'answer',key:'topChanged',value:'no'});return event(s,{type:'submit'},2000);}
test('four assignments counterbalance task, condition and position',()=>{const seq=[0,1,2,3].map(assignment);for(const id of TASKS.map(t=>t.id))for(const c of ['A','B'])for(const i of [0,1])assert.equal(seq.filter(s=>s[i].taskId===id&&s[i].condition===c).length,1);});
test('same task and budget return identical products for A and B',()=>{for(const task of TASKS)for(const budget of ['base','higher']){const a=studyView({taskId:task.id,condition:'A',budget},products);const b=studyView({taskId:task.id,condition:'B',budget},products);assert.deepEqual(a.result,b.result);assert.equal(a.state.budget.shipping_included,true);}});
test('comparison budgets add eligible candidates without inventing a first-rank change',()=>{for(const task of TASKS){const a=studyView({taskId:task.id,budget:'base'},products);const b=studyView({taskId:task.id,budget:'higher'},products);assert.equal(a.topChanged,false);assert.ok(b.result.items.length>a.result.items.length);assert.ok(b.result.items.some(p=>p.id===a.alternative.target.id));}});
test('cannot submit incomplete ratings or inject invalid actions',()=>{let s=newStudy('anon',0,0);assert.equal(canSubmit(s.current),false);for(const e of [{type:'submit'},{type:'select',value:'unknown'},{type:'budget',value:'bad'},{type:'answer',key:'effort',value:6},{type:'answer',key:'name',value:'private'}])assert.deepEqual(event(s,e),s);});
test('lowering budget clears a now-ineligible selection',()=>{let s=event(newStudy('anon',0,0),{type:'budget',value:'higher'});const v=studyView(s.current,products);s=event(s,{type:'select',value:v.alternative.target.id});s=event(s,{type:'budget',value:'base'});assert.equal(s.current.selectedId,null);});
test('completed trial cannot submit twice and break time is excluded from next trial',()=>{const first=finish(newStudy('anon',0,0));assert.equal(first.status,'between');assert.equal(first.trials.length,1);assert.deepEqual(event(first,{type:'submit'},2500),first);const second=nextTrial(first,10000);assert.deepEqual(second.current.answers,{});assert.equal(second.current.startedAt,10000);const complete=finishAt(second,12000);assert.equal(complete.status,'complete');assert.equal(complete.trials[1].durationMs,2000);});
function finishAt(s,now){s=event(s,{type:'select',value:'none'},now);for(const key of ['effort','confidence','pressure'])s=event(s,{type:'answer',key,value:2},now);s=event(s,{type:'answer',key:'topChanged',value:'no'},now);return event(s,{type:'submit'},now);}
test('stopping records incomplete data and prevents further actions',()=>{const s=event(newStudy('anon',1,0),{type:'stop'},700);assert.equal(s.status,'stopped');assert.equal(s.trials.length,0);assert.deepEqual(event(s,{type:'select',value:'none'}),s);const between=event(finish(newStudy('anon',0,0)),{type:'stop'},3000);assert.equal(between.events.at(-1).type,'stop');assert.equal(between.trials.length,1);});
test('exports are snapshots without raw user text and with trial definitions',()=>{const s=finish(newStudy('random-id',0,0));const out=exportStudy(s);assert.equal(out.startedAt,undefined);assert.equal(out.trials[0].startedAt,undefined);assert.equal(out.taskDefinitions.length,2);assert.equal(out.trials[0].comprehensionCorrect,true);out.current.answers.effort=1;assert.equal(s.current.answers.effort,3);assert.equal(out.messages,undefined);assert.ok(out.events.every(e=>!('text' in e)&&!('user' in e)));});
